### ISSUE TITLE
Can't decrypt AES256 encrypted binary file

### ISSUE THREAD

**Issue by KopfKrieg** [isislovecruft/python-gnupg#121]
Hi, somehow I'm unable to decrypt a binary file through python-gnupg. A few month ago this still worked (but I can't remember the exact gnupg-version):

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import gnupg

def main():
    home = os.path.expanduser('~')
    homedir = os.path.join(home, ".gnupg")
    binary = "/usr/bin/gpg2"

    passphrase = ',S!a{`\'M[r%.&#4}vS9Uu^+p&.Q4C;1n'

    gpg = gnupg.GPG(binary=binary, homedir=homedir)

    with open("IYThDruNGyc5iaePDEtKJYCVDTGadj7d", "rb") as fIn:
        dec = gpg.decrypt(fIn.read(), passphrase=passphrase)
        print(dec.data)

if __name__ == '__main__':
    main()
```

Instead of a successfully decrypted file it just throws an error (but, unfortunately, doesn't abort the program)

```
$ ./decrypt-file.py 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/usr/lib/python3.4/site-packages/gnupg/_parsers.py", line 1506, in _handle_status
    super(Crypt, self)._handle_status(key, value)
  File "/usr/lib/python3.4/site-packages/gnupg/_parsers.py", line 1419, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'FAILURE'

b''
$
```

I'm able to decrypt the file if I'm using gpg (without the python stuff): `gpg -d IYThDruNGyc5iaePDEtKJYCVDTGadj7d # works`

This was tested on an up to date Arch Linux installation, using gpg 2.1.8 and libgcrypt 1.6.4, python-gnupg was installed through this package: https://aur.archlinux.org/packages/python-gnupg-isis/

Any suggestions?

**Comment by KopfKrieg** [comment]
Test script (just dropping this here, if anyone wants to play around):

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import os
import gnupg


def main():
    home = os.path.expanduser('~')
    homedir = os.path.join(home, ".gnupg")
    binary = "/usr/bin/gpg2"

    passphrase = 'TotallyRandomKey'
    
    gpg = gnupg.GPG(binary=binary, homedir=homedir)

    enc = gpg.encrypt("Text", passphrase=passphrase, armor=False, encrypt=False, symmetric=True)
    print(enc.data)

    dec = gpg.decrypt(enc.data, passphrase=passphrase)
    print(dec.data)
     


if __name__ == '__main__':
    main()
```

Executed:

```
$ ./crypto_test.py 
b'\x8c\r\x04\t\x03\x02;\xa5BQ\x1fQ\xff\xae\xda\xd2?\x01x$\x8b\xd4^4"\x1aa*\x05c\x1f\x15J\x82\x8c\x9c_\xc0\x9e9\x91\x84\xdc\x1e7l\x88\xc2\xb7\x95;\xc9\xcd\xdad\x9e8\xcb\xd7\x04\x8fj\x967\x99G\xcd(Z/\xd3&%MkG\xcd\xf7D)'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/usr/lib/python3.5/site-packages/gnupg/_parsers.py", line 1506, in _handle_status
    super(Crypt, self)._handle_status(key, value)
  File "/usr/lib/python3.5/site-packages/gnupg/_parsers.py", line 1419, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'FAILURE'

b''
$ 
```

**Comment by isislovecruft** [comment]
Hi @KopfKrieg! Thanks for reporting this! (And much thanks for also providing a test script!)

In #143, I fixed the issue you're having with the `KeyError` for the `FAILURE` status message. This *should* fix your problem. If not, please feel free to reopen this issue.

**Comment by KopfKrieg** [comment]
I'm sorry, but it does not seem to be fixed. Running the testscript gives this result:

´´´
$ python test_encrypt-decrypt.py 
b'\x8c\r\x04\t\x03\x02#\x8edX\x0f\xb3[\x08\xe4\xd2?\x01A\xcc=\x08(6\xaa^\xd61\xec\xed\xc4\x0f\x18\xe5\x88\xaa\x01\n\xf2\xc1\x1d\xde\xd8V1\xa9V\x16\xff4P\x92\xe4x\xc4\x0f;ZX%l\xb6\xe6!\xb2\xf1\xaf+\x8b\xabQ\xac\xd3\xd9\xc6\x87\x92\x984\xd0'
b''
```

Second output shouldn't be emtpy.

Tested on Arch Linux, using python-gnupg v2.2.0-1 (from AUR), gnupg v2.1.17
