### ISSUE TITLE
GPGBase._check_sane_and_get_gpg_version insanity

### ISSUE THREAD

**Issue by doktorstick** [isislovecruft/python-gnupg#144]
gnupg (1.4.0)

I encountered a problem in `_match_version_string` using GPGv1:

``` python
File "/usr/local/lib/python3.4/dist-packages/harness/crypto.py", line 437, in _gpg
  return gnupg.GPG (homedir=self.homedir, binary='/usr/bin/gpg')
File "/usr/local/lib/python3.4/dist-packages/gnupg/gnupg.py", line 154, in __init__
  self.create_trustdb()
File "/usr/local/lib/python3.4/dist-packages/gnupg/gnupg.py", line 158, in create_trustdb
  if self.is_gpg2():
File "/usr/local/lib/python3.4/dist-packages/gnupg/gnupg.py", line 198, in is_gpg2
  return _util._is_gpg2(self.binary_version)
File "/usr/local/lib/python3.4/dist-packages/gnupg/_util.py", line 381, in _is_gpg2
  (major, minor, micro) = _match_version_string(version)
File "/usr/local/lib/python3.4/dist-packages/gnupg/_util.py", line 454, in _match_version_string
  major, minor, micro = int(g[0]), int(g[2]), int(g[4])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

It would seem `_check_sane_and_get_gpg_version` is not fully sanitizing the version nor aborting when it cannot. I still don't know the root cause of the GPG's problem (the system was experiencing general problems, though). What _appears_ to be happening is that for whatever reason, GPG had a hiccup where it exited cleanly but didn't return a parsable version string.

Below is a transcript of my testing / debugging by running snippets of `gnupg` code.

```
$ gpg --list-config --with-colons
cfg:version:1.4.20
cfg:pubkey:1;2;3;16;17
cfg:cipher:1;2;3;4;7;8;9;10;11;12;13
cfg:ciphername:IDEA;3DES;CAST5;BLOWFISH;AES;AES192;AES256;TWOFISH;CAMELLIA128;CAMELLIA192;CAMELLIA256
cfg:digest:1;2;3;8;9;10;11
cfg:digestname:MD5;SHA1;RIPEMD160;SHA256;SHA384;SHA512;SHA224
cfg:compress:0;1;2;3
```

The nominal case.

``` python
$ python3
Python 3.5.1 (default, Dec 26 2015, 18:11:22)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s='''\
... cfg:version:1.4.20
... cfg:pubkey:1;2;3;16;17
... cfg:cipher:1;2;3;4;7;8;9;10;11;12;13
... cfg:ciphername:IDEA;3DES;CAST5;BLOWFISH;AES;AES192;AES256;TWOFISH;CAMELLIA128;CAMELLIA192;CAMELLIA256
... cfg:digest:1;2;3;8;9;10;11
... cfg:digestname:MD5;SHA1;RIPEMD160;SHA256;SHA384;SHA512;SHA224
... cfg:compress:0;1;2;3'''
>>> str(s).partition (':version:')[2]
'1.4.20\ncfg:pubkey:1;2;3;16;17\ncfg:cipher:1;2;3;4;7;8;9;10;11;12;13\ncfg:ciphername:IDEA;3DES;CAST5;BLOWFISH;AES;AES192;AES256;TWOFISH;CAMELLIA128;CAMELLIA192;CAMELLIA256\ncfg:digest:1;2;3;8;9;10;11\ncfg:digestname:MD5;SHA1;RIPEMD160;SHA256;SHA384;SHA512;SHA224\ncfg:compress:0;1;2;3'
>>> str(s).partition (':version:')[2].split('\n')[0]
'1.4.20'
```

If the subprocess returns with a non-zero return code an exception would have been thrown. In this case, it exited with a non-zero, but the partitioning for the version returned something like--'1', '1.4', or '' (the last being the most likely).

Later when it tries to determine if it is GPGv2 (example assumes `''` was set for the version string):

``` python
>>> s = ''
>>> ver = str(s).partition (':version:')[2].split('\n')[0]
>>> ver
''
>>> # Emulating _check_sane*
>>> _VERSION_STRING_REGEX = re.compile('(\d)*(\.)*(\d)*(\.)*(\d)*')
>>> matched = _VERSION_STRING_REGEX.match(ver)
>>> g = matched.groups()
>>> int(g[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by isislovecruft** [comment]
Hi @doktorstick! Thanks for reporting this. I think a good solution would be to throw an exception if the `gpg` process exits with non-zero status. (That is, if something's wrong with your system's `gpg` binary, there's not much this library can do to help.)

Patches welcome.
