### ISSUE TITLE
Using `from __future__ import unicode_literals` in Python 2.7 breaks `verbose` flag pased to GPG class

### ISSUE THREAD

**Issue by gkapkowski** [isislovecruft/python-gnupg#153]
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gnupg
>>> gpg = gnupg.GPG(verbose="guru")
>>> from __future__ import unicode_literals
>>> gpg = gnupg.GPG(verbose="guru")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gnupg/gnupg.py", line 125, in __init__
    ignore_homedir_permissions=ignore_homedir_permissions,
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 221, in __init__
    raise RuntimeError(str(ae))
RuntimeError: 'verbose' must be boolean, string, or 0 <= n <= 9
```

**Comment by isislovecruft** [comment]
Hi @gkapkowski! Thanks for reporting this! It should be fixed in python-gnupg 2.2.0.
