### ISSUE TITLE
OpenBSD fails to instantiate GPG() class.

### ISSUE THREAD

**Issue by dijit** [isislovecruft/python-gnupg#161]
Hello, I'm trying to get the gnupg package working on OpenBSD (5.9).

Details:
python: `Python 3.5.1`
pip: `pip 8.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)`
OS: `OpenBSD echo.e3.drk.sc 5.9 GENERIC.MP#1888 amd64`
gpgdir: `/home/dijit/.gnupg`
gpg: 
```
gpg (GnuPG) 2.1.9
libgcrypt 1.6.5
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

gpg operates normally when called from bash/zsh/fish.

installation from pip:
```
Collecting gnupg
  Downloading gnupg-2.0.2.tar.gz (97kB)
    100% |████████████████████████████████| 102kB 395kB/s 
Collecting psutil>=1.2.1 (from gnupg)
  Downloading psutil-4.3.0.tar.gz (316kB)
    100% |████████████████████████████████| 317kB 650kB/s 
Installing collected packages: psutil, gnupg
  Running setup.py install for psutil ... done
  Running setup.py install for gnupg ... done
Successfully installed gnupg-2.0.2 psutil-4.3.0
~/Vids » python
Python 3.5.1 (default, May 28 2016, 01:29:31) 
[GCC 4.2.1 20070719 ] on openbsd5
Type "help", "copyright", "credits" or "license" for more information.
>>> import gnupg 
>>> gpg = gnupg.GPG()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/gnupg/gnupg.py", line 125, in __init__
    ignore_homedir_permissions=ignore_homedir_permissions,
  File "/usr/local/lib/python3.5/site-packages/gnupg/_meta.py", line 232, in __init__
    self._check_sane_and_get_gpg_version()
  File "/usr/local/lib/python3.5/site-packages/gnupg/_meta.py", line 502, in _check_sane_and_get_gpg_version
    proc.terminate()
  File "/usr/local/lib/python3.5/subprocess.py", line 1769, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/local/lib/python3.5/subprocess.py", line 1764, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
>>> ######################################
>>> gpg = gnupg.GPG(binary='/usr/local/bin/gpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/gnupg-2.0.2_1_g2beac24-py3.5.egg/gnupg/gnupg.py", line 125, in __init__
    ignore_homedir_permissions=ignore_homedir_permissions,
  File "/usr/local/lib/python3.5/site-packages/gnupg-2.0.2_1_g2beac24-py3.5.egg/gnupg/_meta.py", line 232, in __init__
    self._check_sane_and_get_gpg_version()
  File "/usr/local/lib/python3.5/site-packages/gnupg-2.0.2_1_g2beac24-py3.5.egg/gnupg/_meta.py", line 502, in _check_sane_and_get_gpg_version
    proc.terminate()
  File "/usr/local/lib/python3.5/subprocess.py", line 1769, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/local/lib/python3.5/subprocess.py", line 1764, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

Installing from git:
[output.txt](https://github.com/isislovecruft/python-gnupg/files/437241/output.txt)

If there's anything you need me to try let me know please.

Thanks!

**Comment by isislovecruft** [comment]
Hi @dijit! Thanks for reporting this! It seems like your Python has trouble communicating with subprocesses. Is that also true for other subprocesses? E.g. does this fail:

```
#!/usr/bin/env python

import subprocess

cmd = 'ls foo'
proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print(proc.returncode)
```

Also maybe try it with a couple different commands?

Unfortunately, I don't have an OpenBSD box to test this on, and since I'm currently in the process of moving to a different country and my stuff is being shipped, I likely won't have a spare laptop for quite some time.

**Comment by dijit** [comment]
Sorry for the late reply.

So, your snippet fails, I think this is due to `cmd` containing args and the executable.

I tried this:

```python
#!/usr/bin/env python

import subprocess

proc = subprocess.Popen('/home',executable='/bin/ls',stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print(proc.returncode)
```

and:

```python
#!/usr/bin/env python

import subprocess

cmd = '/bin/ls'
proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

and they both return `None`
