### ISSUE TITLE
Support PINENTRY_LAUNCHED

### ISSUE THREAD

**Issue by adeverteuil** [isislovecruft/python-gnupg#98]
Since gpg 2.1, the gpg utility now emits a new status message "PINENTRY_LAUNCHED". python-gnupg raises an exception during signing/decryption because it cannot handle this status code.

I suggest that the list of ignored status messages in Verify.handle_status is extended to include PINENTRY_LAUNCHED.

See also: [the same issue in vinay.sajip's python-gnupg](https://bitbucket.org/vinay.sajip/python-gnupg/issue/26/support-pinentry_launched)

**Comment by isislovecruft** [comment]
@adeverteuil Thanks for reporting this! I'll gladly add it.

**Comment by isislovecruft** [comment]
This is added in my `fix/98-pinentry-launched` branch, which was merged into `develop` for the release of 2.0.1.

**Comment by Rendaw** [comment]
I get a similar error when trying to import a key (with passphrase?):
```
>>> y = x.import_keys(open('x.asc', 'r').read())
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File ".../env/lib/python2.7/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File ".../env/lib/python2.7/site-packages/gnupg/_parsers.py", line 1137, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'PINENTRY_LAUNCHED'
```
`bool(y)` is `True`.  `x.list_keys()` shows the key, but `x.list_keys(True)` returns `[]`.

**Comment by rswgnu** [comment]
Still getting this error using GPG 2.2.17 under Debian Linux (using WSL).

**Comment by rswgnu** [comment]
I should have said the error is coming from gnupg-2.3.1 Python library (Python 3.7) where the _handle_status method of ImportResult does not handle the 'PINENTRY_LAUNCHED' status.  I will check the Python thread on this now.

**Comment by rswgnu** [comment]
Here is the full traceback:

Traceback (most recent call last):
  File "/Miniconda-linux/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Miniconda-linux/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Miniconda-linux/lib/python3.7/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/Miniconda-linux/lib/python3.7/site-packages/gnupg/_parsers.py", line 1294, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'PINENTRY_LAUNCHED'

**Comment by erickeniuk** [comment]
I'm also still getting this error. Is there a resolution to this? Running gnupg 2.3.1 on Python 3.8
